[package]
name = "plygui-cocoa"
version = "0.0.1"
authors = ["Serhii Plyhun <snuk188@gmail.com>"]

[lib]
name = "plygui_cocoa"
path = "src/lib.rs"

#[target.'cfg(target_os = "macos")'.dependencies]
[dependencies]
cocoa = "~0.9"
core-foundation = "~0.3"
objc = "~0.2"
lazy_static = "~0.2"
derive_builder = "~0.5"